version: '3.3'
services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram/foodgram/.env

  web:
    build: 
      context: ../backend/foodgram
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/foodgram/.env
    volumes:
      - media:/code/media
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - media:/code/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - web
volumes:
  postgres_data:
  media:
